# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
install:
  - Rscript -e 'devtools::install_deps("MDFA")'
script:
  - Rscript -e 'devtools::check("MDFA")'
